language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: Webpack.AspNetCore.sln
node_js:
  - "6"
install:
  - cd test/WebSites/BasicWebSite/
  - npm install
  - cd ../../../
script:
  - dotnet build
  - cd test/WebSites/BasicWebSite/
  - npm run start &
  - cd ../../../
  - cd test/Webpack.AspNetCore.Tests.Integration/
  - dotnet test
  - kill %1
